# .github/profiles/profiles.yml
saas_analytics_pipeline:
  target: ci
  outputs:
    ci:
      type: bigquery
      method: service-account        # file-based auth
      project: "{{ env_var('BQ_PROJECT') }}"
      dataset: ci_raw
      keyfile: /tmp/key.json         # ← must be indented under ‘ci’
      location: US
      threads: 1
