name: dbt CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dbt-ci:
    runs-on: ubuntu-latest

    env:
      BQ_PROJECT: ${{ secrets.BQ_PROJECT }}
      BIGQUERY_KEY_JSON: ${{ secrets.BIGQUERY_KEY_JSON }}
      DBT_PROFILES_DIR: ${{ github.workspace }}/.github/profiles

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dbt-bigquery
        run: |
          pip install --upgrade pip
          pip install "dbt-bigquery==1.8.*"

      - name: dbt debug
        run: dbt debug --target ci --profile saas_analytics_pipeline

      - name: dbt build
        if: success()
        run: |
          dbt deps
          dbt build --target ci --profile saas_analytics_pipeline --warn-error
